### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by bhchiang** [scottmangiapane/marketwatch-bot#1]
Does this still work with the MarketWatch VSE? I was able to log in successfully, but calling parse_player and parse_stock resulted in empty orders+stats and 0.0 for the stock. Thanks!

**Comment by scottmangiapane** [comment]
It looks like MarketWatch recently rewrote the UI for their website, which is why parsing is broken... I'll take a look :)

**Comment by bhchiang** [comment]
Thanks so much!

Also, another quick question about logging in: I get a successful response after I submit to the submitlogin.json file (https://github.com/scottmangiapane/marketwatch-bot/blob/master/marketwatch_api.py?utf8=%E2%9C%93#L35), but once I get the url from the response (https://github.com/scottmangiapane/marketwatch-bot/blob/master/marketwatch_api.py?utf8=%E2%9C%93#L39) it directs me to an error login page. The key lines from the html error page are:
```
 <form>
       <input name="landing_page" type="hidden" value="http://marketwatch.com"/>
       <input name="login_realm" type="hidden" value="default"/>
       <input name="login_template" type="hidden" value="default"/>
       <fieldset>
        <ul class="login_errorbox hidden" id="loginErrorUl">
         <li class="hidden" id="general_error">
          There was an error accessing this page. Please try again after sometime. If you have any questions,
          <a href="null" target="_blank">
           please contact Customer Service.
          </a>
         </li>
         <li class="hidden" id="no_email_username">
          Please enter your email address.
         </li>
         <li class="hidden" id="no_password">
          Please enter your password.
         </li>
         <li class="hidden" id="invalid_login_2times">
          Please try again. We were unable to find this email and password combination.
         </li>
         <li class="hidden" id="invalid_login_3times">
          Please try again. We were unable to find this email and password combination.
          <br/>
          <a href="username_forgot_standalone.html">
          </a>
          <br/>
          <a href="password_forgot_standalone.html">
           Forgot your password?
          </a>
         </li>
         <li class="hidden" id="verify_free_reg_user">
          <a href="verify_email_standalone.html">
          </a>
         </li>
```
I'm unable to access the VSE afterwards (i.e. getting the portfolio page of a game).

Do you know if this is normal behavior?
